[program:queue-worker]
command=php /var/www/backend/artisan queue:work --sleep=1 --tries=3 --timeout=90
directory=/var/www/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/queue-worker.err.log
stdout_logfile=/var/log/supervisor/queue-worker.out.log

[program:websockets]
command=php /var/www/backend/artisan websockets:serve --host=0.0.0.0 --port=6001
directory=/var/www/backend
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/websockets.err.log
stdout_logfile=/var/log/supervisor/websockets.out.log
